"""Phase 4: gross-of-costs backtest of the selected pair over the trading period.

Usage:  python scripts/run_backtest_gross.py

Uses the pair, alpha, and beta recorded in data/dataset_manifest.json, the
signal rules in src/config.py (ADR-003/ADR-009), and the accounting rules in
ADR-010. No transaction costs are applied. Writes docs/results_gross.json
(deterministic, so its SHA-256 identifies the frozen gross result) and
docs/results_gross.md.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src import config  # noqa: E402
from src.backtest import compute_metrics, run_backtest  # noqa: E402
from src.data import align_prices, file_sha256, load_raw, slice_period  # noqa: E402
from src.signal import generate_signal  # noqa: E402

CAPITAL = 100_000.0
JSON_PATH = config.PROJECT_ROOT / "docs" / "results_gross.json"
MD_PATH = config.PROJECT_ROOT / "docs" / "results_gross.md"


def main() -> None:
    manifest = json.loads(config.MANIFEST_PATH.read_text(encoding="utf-8"))
    sha = file_sha256(config.RAW_PRICES_PATH)
    if sha != manifest["raw_file_sha256"]:
        raise RuntimeError("raw price file does not match the snapshot used for pair selection")
    pair = next(p for p in manifest["pairs_tested"] if p["pair"] == manifest["selected_pair"])
    y, x, alpha, beta = pair["y"], pair["x"], pair["alpha"], pair["beta"]

    raw = load_raw(config.RAW_PRICES_PATH)
    adj_full, _ = align_prices(raw["Adj Close"], config.UNIVERSE)
    close_full = raw["Close"].loc[adj_full.index, list(config.UNIVERSE)]

    signal = generate_signal(
        np.log(adj_full), y, x, alpha, beta, config.TRADING_START, config.TRADING_END
    )
    adj = slice_period(adj_full, config.TRADING_START, config.TRADING_END)
    close = slice_period(close_full, config.TRADING_START, config.TRADING_END)
    result = run_backtest(signal["target_position"], adj, close, y, x, beta, CAPITAL)

    if not np.isclose(result.trades["pnl"].sum(), result.daily["pnl"].sum(), atol=1e-6):
        raise RuntimeError("trade P&L does not reconcile with daily P&L")
    metrics = compute_metrics(result.daily["pnl"], result.trades, result.executions, CAPITAL)
    metrics["time_in_market"] = float((result.daily["position"] != 0).mean())
    metrics["forced_closes"] = int(result.trades["forced_close"].sum())

    trades = result.trades.copy()
    for col in ("entry_date", "exit_date"):
        trades[col] = trades[col].dt.strftime("%Y-%m-%d")
    payload = {
        "description": "Gross-of-costs backtest (no transaction costs). Frozen per ADR-010.",
        "raw_file_sha256": sha,
        "pair": {"y": y, "x": x, "alpha": alpha, "beta": beta},
        "parameters": {
            "trading_period": [config.TRADING_START, config.TRADING_END],
            "zscore_window": config.ZSCORE_WINDOW,
            "entry_z": config.ENTRY_Z,
            "exit_z": config.EXIT_Z,
            "capital": CAPITAL,
            "execution": "target at close t, executed at close t+1",
        },
        "metrics": metrics,
        "trades": json.loads(trades.to_json(orient="records")),
    }
    JSON_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    json_sha = hashlib.sha256(JSON_PATH.read_bytes()).hexdigest()

    m = metrics
    rows = "\n".join(
        f"| {t.trade_id} | {'long' if t.direction == 1 else 'short'} spread | "
        f"{t.entry_date.date()} | {t.exit_date.date()} | {t.holding_days} | "
        f"{t.entry_notional:,.0f} | {t.pnl:,.2f} | {'yes' if t.forced_close else ''} |"
        for t in result.trades.itertuples()
    )
    MD_PATH.write_text(f"""# Gross Backtest Results — {y}/{x}, before transaction costs

> Generated by `scripts/run_backtest_gross.py`. Do not edit by hand.
> **Gross of costs only.** Recorded before any cost model was written and frozen
> per DECISIONS.md ADR-010: it may not be changed after the net result is seen.
> `results_gross.json` SHA-256: `{json_sha}`. Raw data SHA-256: `{sha}`.

**Read with the disclosures in DECISIONS.md ADR-008:** {y}/{x} was the best of 28
searched pairs and does not survive Holm correction (p = 0.142). Cointegration is
not detected in the trading period (Engle-Granger p = 0.223).

Setup: trading period {adj.index[0].date()} to {adj.index[-1].date()} ({m["n_days"]} days);
hedge ratio beta = {beta:.4f} and alpha = {alpha:.4f} from the 2016–2020 formation
period; 60-day z-score, entry at |z| ≥ 2.0, exit at the 0.5 band (ADR-009);
$100,000 gross notional per trade, not compounded; executed at the next day's close.

| Metric | Gross of costs |
|---|---:|
| Total P&L | ${m["total_pnl"]:,.2f} |
| Total return (on $100,000) | {m["total_return"]:.2%} |
| Annualized return | {m["annualized_return"]:.2%} |
| Annualized volatility | {m["annualized_volatility"]:.2%} |
| Sharpe ratio | {m["sharpe_ratio"]:.2f} |
| Max drawdown | {m["max_drawdown"]:.2%} |
| Number of trades (round trips) | {m["n_trades"]} |
| Win rate | {m["win_rate"]:.1%} |
| Average P&L per trade | ${m["avg_trade_pnl"]:,.2f} |
| Average holding period (trading days) | {m["avg_holding_days"]:.1f} |
| Time in market | {m["time_in_market"]:.1%} |
| Turnover (traded notional / capital / year) | {m["turnover_per_year"]:.1f}x |
| Trades closed by the end of the period | {m["forced_closes"]} |

## All trades

| # | Direction | Entry | Exit | Days | Entry notional ($) | Gross P&L ($) | Forced close |
|---:|---|---|---|---:|---:|---:|---|
{rows}
""", encoding="utf-8")

    print(MD_PATH.read_text(encoding="utf-8"))
    print(f"results_gross.json SHA-256: {json_sha}")


if __name__ == "__main__":
    main()
