"""Phases 1-2: retrieve prices, test all candidate pairs on the formation period, select one.

Usage:  python scripts/select_pair.py [--refresh]

Reuses data/raw/prices_raw.csv if it exists (DECISIONS.md ADR-007); pass
--refresh to download again. Writes the full pair-testing record to
data/dataset_manifest.json and docs/pair_selection.md. Trading-period data
is validated but not analyzed here.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src import config  # noqa: E402
from src.cointegration import (  # noqa: E402
    run_all_pair_tests,
    select_pair,
    weak_relationship_flags,
)
from src.data import (  # noqa: E402
    align_prices,
    download_prices,
    file_sha256,
    load_raw,
    save_raw,
    slice_period,
    validate_prices,
)

RAW_META_PATH = config.RAW_PRICES_PATH.with_suffix(".meta.json")


def get_raw_prices(refresh: bool) -> tuple[pd.DataFrame, dict]:
    if refresh or not config.RAW_PRICES_PATH.exists():
        import yfinance as yf

        prices, sources = download_prices(
            config.UNIVERSE, config.SAMPLE_START, config.SAMPLE_END
        )
        save_raw(prices, config.RAW_PRICES_PATH)
        meta = {
            "download_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "yfinance_version": yf.__version__,
            "retrieval_method_by_ticker": sources,
        }
        RAW_META_PATH.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
        print(f"Downloaded prices to {config.RAW_PRICES_PATH.relative_to(config.PROJECT_ROOT)}")
    else:
        print(f"Reusing {config.RAW_PRICES_PATH.relative_to(config.PROJECT_ROOT)}")
    meta = json.loads(RAW_META_PATH.read_text(encoding="utf-8"))
    meta["sha256"] = file_sha256(config.RAW_PRICES_PATH)
    return load_raw(config.RAW_PRICES_PATH), meta


def fmt_p(p: float) -> str:
    return f"{p:.2e}" if p < 1e-3 else f"{p:.4f}"


def pair_table_markdown(results: pd.DataFrame) -> str:
    header = (
        "| Rank | Pair (Y/X) | N | EG stat | 5% crit | p raw | p Holm | p Bonferroni "
        "| beta | alpha | p raw (reverse) |\n"
        "|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n"
    )
    lines = [
        f"| {r.rank} | {r.pair} | {r.nobs} | {r.eg_stat:.3f} | {r.crit_5pct:.3f} "
        f"| {fmt_p(r.p_raw)} | {fmt_p(r.p_holm)} | {fmt_p(r.p_bonferroni)} "
        f"| {r.beta:.4f} | {r.alpha:.4f} | {fmt_p(r.p_raw_reverse)} |"
        for r in results.itertuples()
    ]
    return header + "\n".join(lines) + "\n"


def write_report(results, selected, flags, formation, report, meta) -> None:
    status = "TRIGGERED: " + "; ".join(flags) if flags else "not triggered"
    text = f"""# Pair Selection — Formation Period Results

> Generated by `scripts/select_pair.py`. Do not edit by hand.
> Raw data SHA-256: `{meta["sha256"]}` (downloaded {meta["download_utc"]},
> yfinance {meta["yfinance_version"]}).

- **Test:** Engle-Granger (`statsmodels` `coint`, constant, AIC lags) on log
  adjusted closes; Y is the alphabetically first ticker (DECISIONS.md ADR-002).
- **Formation period:** {formation.index[0].date()} to {formation.index[-1].date()},
  {len(formation)} trading days common to all tickers.
- **Pairs tested:** {len(results)} (every pair of {len(config.UNIVERSE)} tickers).
  Holm and Bonferroni adjustments are over all {len(results)} tests.
- **Dates dropped by alignment (full sample):** {report.rows_dropped} of
  {report.rows_before}; missing values by ticker: {report.missing_by_ticker}.
- **`p raw (reverse)`** swaps Y and X. It is reported as a robustness check
  and is not used for selection.
- **beta, alpha:** OLS of log(Y) on a constant and log(X) over the formation period.

{pair_table_markdown(results)}
**Selected pair (lowest raw p-value):** {selected["pair"]} — EG stat
{selected["eg_stat"]:.3f}, raw p {fmt_p(selected["p_raw"])}, Holm p
{fmt_p(selected["p_holm"])}, Bonferroni p {fmt_p(selected["p_bonferroni"])},
beta {selected["beta"]:.4f}.

**ADR-002 weak-relationship rule:** {status}.
"""
    config.PAIR_TESTS_PATH.write_text(text, encoding="utf-8")


def write_manifest(results, selected, flags, full, formation, report, meta) -> None:
    def clean(v):
        return v.item() if isinstance(v, np.generic) else v

    manifest = {
        "source": "yfinance",
        "yfinance_version": meta["yfinance_version"],
        "download_utc": meta["download_utc"],
        "raw_file": str(config.RAW_PRICES_PATH.relative_to(config.PROJECT_ROOT).as_posix()),
        "raw_file_sha256": meta["sha256"],
        "retrieval_method_by_ticker": meta["retrieval_method_by_ticker"],
        "price_field": "Adj Close",
        "candidate_universe": list(config.UNIVERSE),
        "sample_period": {"start": config.SAMPLE_START, "end": config.SAMPLE_END},
        "formation_period": {"start": config.FORMATION_START, "end": config.FORMATION_END},
        "trading_period": {"start": config.TRADING_START, "end": config.TRADING_END},
        "aligned_sample": {
            "first_date": str(full.index[0].date()),
            "last_date": str(full.index[-1].date()),
            "rows": len(full),
            "rows_dropped_by_alignment": report.rows_dropped,
            "missing_by_ticker": report.missing_by_ticker,
        },
        "formation_rows": len(formation),
        "test": "Engle-Granger (statsmodels coint, trend='c', autolag='aic') on log Adj Close",
        "n_pairs_tested": len(results),
        "pairs_tested": [
            {k: clean(v) for k, v in row.items()} for row in results.to_dict(orient="records")
        ],
        "selected_pair": selected["pair"],
        "selection_rationale": "Lowest raw Engle-Granger p-value in the formation period "
        "(pre-registered rule, DECISIONS.md ADR-002).",
        "weak_relationship_flags": flags,
    }
    config.MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--refresh", action="store_true", help="download prices again")
    args = parser.parse_args()

    raw, meta = get_raw_prices(args.refresh)
    validate_prices(raw)
    full, report = align_prices(raw["Adj Close"], config.UNIVERSE)
    formation = slice_period(full, config.FORMATION_START, config.FORMATION_END)

    results = run_all_pair_tests(np.log(formation))
    selected = select_pair(results)
    flags = weak_relationship_flags(selected)

    write_report(results, selected, flags, formation, report, meta)
    write_manifest(results, selected, flags, full, formation, report, meta)

    print(f"Aligned sample: {full.index[0].date()} .. {full.index[-1].date()} ({len(full)} rows,"
          f" {report.rows_dropped} dropped)")
    print(f"Formation rows: {len(formation)}; pairs tested: {len(results)}")
    print(f"Selected pair: {selected['pair']}  raw p={fmt_p(selected['p_raw'])}"
          f"  Holm p={fmt_p(selected['p_holm'])}")
    print("Weak-relationship rule:", "; ".join(flags) if flags else "not triggered")
    print(f"Wrote {config.PAIR_TESTS_PATH.relative_to(config.PROJECT_ROOT)} and "
          f"{config.MANIFEST_PATH.relative_to(config.PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
