"""Out-of-sample stability diagnostic for the selected pair (DECISIONS.md ADR-002, ADR-008).

Usage:  python scripts/stability_check.py

Reruns the pre-registered Engle-Granger test on the trading period
(2021-2025) for the pair recorded in data/dataset_manifest.json. This is a
diagnostic only: it never changes the pair, hedge ratio, or any parameter.
Writes docs/stability_check.md. No positions, trades, or P&L are computed.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
from statsmodels.tsa.stattools import adfuller

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src import config  # noqa: E402
from src.cointegration import engle_granger, hedge_ratio  # noqa: E402
from src.data import align_prices, file_sha256, load_raw, slice_period  # noqa: E402

REPORT_PATH = config.PROJECT_ROOT / "docs" / "stability_check.md"


def main() -> None:
    manifest = json.loads(config.MANIFEST_PATH.read_text(encoding="utf-8"))
    sha = file_sha256(config.RAW_PRICES_PATH)
    if sha != manifest["raw_file_sha256"]:
        raise RuntimeError("raw price file does not match the snapshot used for pair selection")
    selected = next(p for p in manifest["pairs_tested"] if p["pair"] == manifest["selected_pair"])
    y_name, x_name = selected["y"], selected["x"]

    full, _ = align_prices(load_raw(config.RAW_PRICES_PATH)["Adj Close"], config.UNIVERSE)
    trading = np.log(slice_period(full, config.TRADING_START, config.TRADING_END))
    y, x = trading[y_name], trading[x_name]

    # Pre-registered: same test, same ordering, trading-period data.
    eg = engle_granger(y, x)
    eg_reverse = engle_granger(x, y)
    alpha_t, beta_t = hedge_ratio(y, x)

    # Supplementary (not pre-registered): is the spread actually traded -- built with
    # the fixed formation alpha and beta -- stationary over the trading period?
    fixed_spread = y - selected["beta"] * x - selected["alpha"]
    adf_stat, adf_p, *_ = adfuller(
        fixed_spread, regression="c", autolag="AIC", result_object=False
    )

    verdict = (
        f"cointegration {'is' if eg.pvalue <= config.SIGNIFICANCE_LEVEL else 'is NOT'} "
        f"detected at 5% in the trading period"
    )
    text = f"""# Out-of-Sample Stability Check — {manifest["selected_pair"]}

> Generated by `scripts/stability_check.py`. Do not edit by hand. Diagnostic only
> (DECISIONS.md ADR-002): it does not change the pair or any parameter, and no
> trades or P&L are computed here. Raw data SHA-256 `{sha}`.

Trading period: {trading.index[0].date()} to {trading.index[-1].date()}, {len(trading)} days.

## Pre-registered: Engle-Granger test rerun on the trading period

| | Formation (2016–2020) | Trading (2021–2025) |
|---|---:|---:|
| EG statistic (Y = {y_name}) | {selected["eg_stat"]:.3f} | {eg.statistic:.3f} |
| 5% critical value | {selected["crit_5pct"]:.3f} | {eg.crit_5pct:.3f} |
| p-value | {selected["p_raw"]:.4f} | {eg.pvalue:.4f} |
| p-value, reverse ordering | {selected["p_raw_reverse"]:.4f} | {eg_reverse.pvalue:.4f} |
| OLS beta (log {y_name} on log {x_name}) | {selected["beta"]:.4f} | {beta_t:.4f} |
| OLS alpha | {selected["alpha"]:.4f} | {alpha_t:.4f} |

Result: {verdict}.

## Supplementary (not pre-registered): stationarity of the traded spread

The strategy trades the spread built with the **formation** coefficients, which are
never re-estimated: `s = log {y_name} - {selected["beta"]:.4f} * log {x_name} - ({selected["alpha"]:.4f})`.
ADF test (constant, AIC lags) on that fixed spread over the trading period:
statistic {adf_stat:.3f}, p-value {adf_p:.4f}. Spread mean {fixed_spread.mean():.4f},
standard deviation {fixed_spread.std():.4f} (formation-period residuals have mean 0 by construction).
"""
    REPORT_PATH.write_text(text, encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()
